CREATE database Projects;
use Projects;

SELECT * from diseases;
ALTER TABLE diseases RENAME COLUMN DESCRIPTION1 TO SYMPTOMS;
ALTER TABLE diseases RENAME COLUMN SEVERITY1 TO SEVERITY;
ALTER TABLE diseases RENAME COLUMN PATIENT TO PATIENT_ID;

SELECT * from medicationn;
ALTER TABLE medicationn RENAME COLUMN PATIENT TO PATIENT_ID;
ALTER TABLE medicationn RENAME COLUMN DESCRIPTION TO MEDICINE_DESCRIPTION;

SELECT * from patients_data;
ALTER TABLE patients_data RENAME COLUMN Id TO PATIENT_ID;
ALTER TABLE patients_data RENAME COLUMN LAST TO LAST_NAME;
ALTER TABLE patients_data RENAME COLUMN FIRST TO FIRST_NAME;

ALTER TABLE patients_data
ADD COLUMN Birthdate_date DATE,
ADD COLUMN Birthdate_time TIME;
SET SQL_SAFE_UPDATES = 0;
-- Run the update query
UPDATE patients_data
SET Birthdate_date = DATE(BIRTHDATE),
    Birthdate_time = TIME(BIRTHDATE);
-- Re-enable safe update mode (if desired)
SET SQL_SAFE_UPDATES = 1;

ALTER TABLE patients_data DROP COLUMN BIRTHDATE;

SELECT * from testsnn;
ALTER TABLE testsnn RENAME COLUMN PATIENT TO PATIENT_ID;
ALTER TABLE testsnn RENAME COLUMN SOP_DESCRIPTION TO TEST_DESCRIPTION;
ALTER TABLE testsnn RENAME COLUMN MODALITY_DESCRIPTION TO TEST_NAME;


